<!DOCTYPE html>
<html>

<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Jefes de catedra</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
  <link rel='stylesheet' type='text/css' media='screen' href='/estilo/estilo.css'>
  <link rel='stylesheet' type='text/css' media='screen' href='<?= App\Core\Http::url('estilo/formulario.css') ?>'>
  <script src="<?= App\Core\Http::url('estilo/autocompletar.js') ?>" defer data-buscador-url="<?= App\Core\Http::url('buscador') ?>"></script>
</head>