<div class="conteiner">
  <form method="post" action="<?= $formulario->accion ?>">

    <?php foreach ($formulario->datos as $dato) {
        require './app/template/input.phtml';
    } ?>

  <div class="botonera">

    <button type="reset"><?= $formulario->borrar ?? 'recetear formulario' ?></button>
    <button type="submit"><?= $formulario->aceptar ?? 'aceptar' ?></button>
  </div>

  </form>
</div>