<div class='inputs-span' key='<?= $dato->id ?>'>
  <span><?= $dato->requerido ? '*' : '' ?></span>
  <div class='inputs-entero'>
    <input 
      type="<?= $dato->tipo ?? 'text' ?>"
      id="<?= $dato->id?>"
      name="<?= $dato->id?>"
      value="<?= $dato->valor ?? '' ?>"
      placeholder=' '
    >
    <label 
      for="<?= $dato->id?>"
    >
    <?= $dato->label?>
  </label>
  </div>
  <span><?=$dato->error ?? ''?></span>
</div>